### ISSUE TITLE
Question regarding pose detection being displayed on screen 

### ISSUE THREAD

**Issue by Jordan-Terzian** [ThatSongKim/vision-camera-pose-detector#1]
Hi, 

been playing around with your library and it's super good, well done!

Was just wondering, would you know how to make it such that the poses are displayed on screen using skia or some other canvas package? I've been attempting this and have had no luck so far. 

Thank you for your time

**Comment by thatsongkim** [comment]
Sorry, I don't know anything about it because I didn't need that feature.
